export const OK_STATUSES: ReadonlySet<string> = new Set([
  "completed",
  "complete",
  "success",
  "successful",
  "ok",
  "settled",
  "done",
  "posted",
  "cleared",
  "approved",
  "paid",
]);

export const INCOME_DIRECTIONS: ReadonlySet<string> = new Set([
  "in",
  "credit",
  "income",
  "deposit",
  "incoming",
  "received",
  "received_amount",
  "+",
  "1",
]);

export const EXPENSE_DIRECTIONS: ReadonlySet<string> = new Set([
  "out",
  "debit",
  "expense",
  "withdrawal",
  "outgoing",
  "sent",
  "spent",
  "-",
  "0",
]);

export const PATTERNS = {
  date: [
    /\bdate\b/,
    /\bfecha\b/,
    /\btime\b/,
    /\bwhen\b/,
    /timestamp/,
    /created/,
    /finished/,
    /occurred/,
  ],
  amount: [/amount/, /monto/, /\btotal\b/, /\bvalue\b/, /\bsum\b/, /importe/],
  amountExclude: [
    /fee/,
    /tax/,
    /charge/,
    /commission/,
    /\brate\b/,
    /balance/,
    /running/,
    /exchange/,
  ],
  debit: [/\bdebit\b/, /\bdebito\b/, /withdrawal/, /\bspent\b/, /\bgasto\b/],
  credit: [/\bcredit\b/, /\bcredito\b/, /deposit/, /received/, /\bingreso\b/],
  currency: [/currency/, /moneda/, /\bccy\b/, /\bcur\b/, /\bcoin\b/],
  currencyExclude: [/fee/, /tax/, /charge/],
  description: [
    /description/,
    /descripcion/,
    /narration/,
    /reference/,
    /details/,
    /concept/,
    /merchant/,
    /payee/,
    /memo/,
    /detalle/,
    /concepto/,
    /\bnote\b/,
    /target.?name/,
    /beneficiary/,
    /recipient/,
    /\bpayer\b/,
  ],
  direction: [/direction/, /\bflow\b/, /\bin\/out\b/, /\btype\b/],
  status: [/\bstatus\b/, /\bstate\b/],
  externalId: [
    /transaction.?id/,
    /\btx.?id\b/,
    /\btxn.?id\b/,
    /reference.?id/,
    /\bref(?:erence)?\b/,
    /\b(?:transfer|payment).?id\b/,
    /^id$/,
  ],
} as const;
